/**
 * WDK Bundle Configuration
 * Generated by @tetherto/wdk-worklet-bundler
 *
 * For documentation see: https://github.com/tetherto/wdk-worklet-bundler
 */

module.exports = {
  // Network mappings
  // Map logical network names to WDK wallet packages

  // Official example
  // networks: {
  //   ethereum: {
  //     blockchain: 'ethereum',
  //     config: {
  //       chainId: 11155111, // Sepolia testnet
  //       provider: 'https://rpc.sepolia.org',
  //       bundlerUrl: 'https://api.candide.dev/public/v3/11155111',
  //       paymasterUrl: 'https://api.candide.dev/public/v3/11155111',
  //       paymasterAddress: '0x8b1f6cb5d062aa2ce8d581942bbb960420d875ba',
  //       transferMaxFee: 5000000,
  //       paymasterToken: {
  //         address: '0xaA8E23Fb1079EA71e0a56F48a2aA51851D8433D0', // USDT on Sepolia
  //       },
  //     },
  //   },
  //   // Add more networks as needed
  // },

  networks: {
    bitcoin: { package: '@tetherto/wdk-wallet-btc' },
    spark: { package: '@tetherto/wdk-wallet-spark' },
    ethereum: { package: '@tetherto/wdk-wallet-evm-erc-4337' },
    arbitrum: { package: '@tetherto/wdk-wallet-evm-erc-4337' },
    polygon: { package: '@tetherto/wdk-wallet-evm-erc-4337' },
    tron: { package: '@tetherto/wdk-wallet-tron' },
  },

  // Output paths (optional, defaults shown)
  output: {
    bundle: './.wdk-bundle/wdk-worklet.bundle.js',
    types: './.wdk/index.d.ts',
  },

  // Build options (optional)
  options: {
    // minify: false,
    // sourceMaps: false,
    // FIXME: Should I adjust it for production?
    targets: [
      'ios-arm64',
      'ios-arm64-simulator',
      'ios-x64-simulator',
      'android-arm64',
      'android-arm',
      'android-ia32',
      'android-x64',
    ],
  },
};
